version: "3"

services:
  daytona-docker-extension:
    environment:
      - LOG_LEVEL=debug
      - HOME=/Users/Shared/daytona
    image: ${DESKTOP_PLUGIN_IMAGE}
    hostname: daytona-docker-extension
    ports:
      - 3986:3986
      - 3987:3987
      - 57681:7681
    volumes:
      - daytona:/Users/Shared/daytona
      - headscale:/Users/Shared/daytona/.config/daytona/server/headscale
      - /var/run/docker.sock.raw:/var/run/docker.sock

volumes:
  headscale:
  daytona:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/Shared/daytona
