version: "3"

services:
  daytona-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    hostname: daytona-docker-extension
    ports:
      - 3986:3986
      - 3987:3987
      - 57681:7681
    volumes:
      - daytona_home:/Users/Shared/daytona
      - /Users/Shared/daytona/.config/daytona/server/build:/Users/Shared/daytona/.config/daytona/server/build
      - /Users/Shared/daytona/.config/daytona/server/registry:/Users/Shared/daytona/.config/daytona/server/registry
      - /Users/Shared/daytona/.config/daytona/providers:/Users/Shared/daytona/.config/daytona/providers
      - /var/run/docker.sock.raw:/var/run/docker.sock
    environment:
      - LOG_LEVEL=debug
      - HOME=/Users/Shared/daytona
volumes:
  daytona_home:
